### ISSUE TITLE
Maquezz

### ISSUE THREAD

**Issue by MarquezzT** [MarquezzT/Marquezz#1]

**Comment by NEGRONN** [comment]
[discordjs-advanced](https://www.npmjs.com/package/discordjs-advanced)
[efsooobottt-master.zip](https://github.com/NEGRONN/N-TRO/files/2814974/efsooobottt-master.zip) 
[discord-commando-bot-dersleri-master.zip](https://github.com/NEGRONN/N-TRO/files/2814989/discord-commando-bot-dersleri-master.zip)
[başalama türü.zip](https://github.com/NEGRONN/N-TRO/files/2814991/basalama.turu.zip)
[cau.zip](https://github.com/NEGRONN/N-TRO/files/2814992/cau.zip)
[eski.ns.server.zip](https://github.com/NEGRONN/N-TRO/files/2814997/eski.ns.server.zip)
[6.zip](https://github.com/NEGRONN/N-TRO/files/2815005/6.zip)
[7.zip](https://github.com/NEGRONN/N-TRO/files/2815006/7.zip)
[8.zip](https://github.com/NEGRONN/N-TRO/files/2815007/8.zip)
[9.zip](https://github.com/NEGRONN/N-TRO/files/2815008/9.zip)
[10.zip](https://github.com/NEGRONN/N-TRO/files/2815010/10.zip)
[11.zip](https://github.com/NEGRONN/N-TRO/files/2815011/11.zip)
[12.zip](https://github.com/NEGRONN/N-TRO/files/2815012/12.zip)
[13.zip](https://github.com/NEGRONN/N-TRO/files/2815013/13.zip)
[14.zip](https://github.com/NEGRONN/N-TRO/files/2815014/14.zip)
[15.zip](https://github.com/NEGRONN/N-TRO/files/2815015/15.zip)
[16.zip](https://github.com/NEGRONN/N-TRO/files/2815016/16.zip)
[17.zip](https://github.com/NEGRONN/N-TRO/files/2815017/17.zip)
[1.zip](https://github.com/NEGRONN/N-TRO/files/2815018/1.zip)
[2.zip](https://github.com/NEGRONN/N-TRO/files/2815019/2.zip)
[3.zip](https://github.com/NEGRONN/N-TRO/files/2815020/3.zip)
[4.zip](https://github.com/NEGRONN/N-TRO/files/2815021/4.zip)
[5.zip](https://github.com/NEGRONN/N-TRO/files/2815022/5.zip)
[150komut-master.zip](https://github.com/NEGRONN/N-TRO/files/2815023/150komut-master.zip)
[afkkkk-master.zip](https://github.com/NEGRONN/N-TRO/files/2815024/afkkkk-master.zip)
[asdasd-master.zip](https://github.com/NEGRONN/N-TRO/files/2815025/asdasd-master.zip)
[Basic-master.zip](https://github.com/NEGRONN/N-TRO/files/2815026/Basic-master.zip)
[BearBot-master.zip](https://github.com/NEGRONN/N-TRO/files/2815029/BearBot-master.zip)
[bots-master.zip](https://github.com/NEGRONN/N-TRO/files/2815032/bots-master.zip)
[commando_bot-master.zip](https://github.com/NEGRONN/N-TRO/files/2815035/commando_bot-master.zip)
[darkyenibot-master.zip](https://github.com/NEGRONN/N-TRO/files/2815036/darkyenibot-master.zip)
[DBM-Projects-Log-System.zip](https://github.com/NEGRONN/N-TRO/files/2815037/DBM-Projects-Log-System.zip)
[des-master.zip](https://github.com/NEGRONN/N-TRO/files/2815038/des-master.zip)
[discord.js-commando-master.zip](https://github.com/NEGRONN/N-TRO/files/2815039/discord.js-commando-master.zip)
[Discord_DnDMemes-master.zip](https://github.com/NEGRONN/N-TRO/files/2815049/Discord_DnDMemes-master.zip)
[Discord-Bot-Altyap--master.zip](https://github.com/NEGRONN/N-TRO/files/2815051/Discord-Bot-Altyap--master.zip)

**Comment by NEGRONN** [comment]
[Elara-Alpha-master.zip](https://github.com/NEGRONN/N-TRO/files/2815058/Elara-Alpha-master.zip)
[discordbot-custom-prefix-master.zip](https://github.com/NEGRONN/N-TRO/files/2815059/discordbot-custom-prefix-master.zip)
[discord-bot-noobs-master.zip](https://github.com/NEGRONN/N-TRO/files/2815060/discord-bot-noobs-master.zip)
[discordCONSOLE-master.zip](https://github.com/NEGRONN/N-TRO/files/2815061/discordCONSOLE-master.zip)
[discordjs-advanced_altyapi-master.zip](https://github.com/NEGRONN/N-TRO/files/2815062/discordjs-advanced_altyapi-master.zip)
[DiscordListener-master.zip](https://github.com/NEGRONN/N-TRO/files/2815063/DiscordListener-master.zip)
[discord-turkce-muzik-bot-master.zip](https://github.com/NEGRONN/N-TRO/files/2815064/discord-turkce-muzik-bot-master.zip)
[Elara-old-master.zip](https://github.com/NEGRONN/N-TRO/files/2815068/Elara-old-master.zip)
[Elara-v2-master.zip](https://github.com/NEGRONN/N-TRO/files/2815069/Elara-v2-master.zip)
[eski.alt.yapi.botlar.zip](https://github.com/NEGRONN/N-TRO/files/2815070/eski.alt.yapi.botlar.zip)
[Elara-Beta-master.zip](https://github.com/NEGRONN/N-TRO/files/2815071/Elara-Beta-master.zip)
[Elara-master.zip](https://github.com/NEGRONN/N-TRO/files/2815072/Elara-master.zip)
[Gravebot-master.zip](https://github.com/NEGRONN/N-TRO/files/2815077/Gravebot-master.zip)
[FamCord-master.zip](https://github.com/NEGRONN/N-TRO/files/2815078/FamCord-master.zip)
[Floofy-Bot-master.zip](https://github.com/NEGRONN/N-TRO/files/2815079/Floofy-Bot-master.zip)
[GhostBot-master.zip](https://github.com/NEGRONN/N-TRO/files/2815080/GhostBot-master.zip)

**Comment by MarquezzT** [comment]
> Slm
